Add Ruby Tests
cfe-lab/gotoh pull request #1
Opened 2020-02-25 18:21 UTC by jamesnakagawa

Mirrors the Python tests, with a couple of changes:

- Ruby version of this library does not return the score
- Ruby version of this library does not provide for the parameter `use_terminal_gap_penalty`, which is always 0 in this version
- For insertions and deletions, gaps are placed at the beginning of the aligned string for some reason.

An example of the last point above:

```
reference: 
TGGAAGGGCTAATTCACTCCCAACGAAGACAAGATATCCTTGATCTGTGGATCTACCACACA
deletion:         ^^^^^^

sequence:
TGGAAGGGCTAATTCACTGAAGACAAGATATCCTTGATCTGTGGATCTACCACACA

in python:
TGGAAGGGCTAATTCACT------GAAGACAAGATATCCTTGATCTGTGGATCTACCACACA

in ruby:
------TGGAAGGGCTAATTCACTGAAGACAAGATATCCTTGATCTGTGGATCTACCACACA
```

2020-02-25 18:24 UTC, nathanielknight commented on test_alignment.rb
> +  # end
If these tests are useful, we should add them. If they're not, they should be deleted.

2020-02-25 18:24 UTC, nathanielknight requested changes
I would prefer if we didn't check-in any commented-out code.

2020-02-25 18:36 UTC, donkirkby requested changes

2020-02-25 18:36 UTC, donkirkby commented on test_alignment.rb
> +  def test_align_it_aa_match
This test doesn't mean anything without the score. It was just showing that the Python amino acid alignment used a variable scoring matrix.

2020-02-25 18:36 UTC, donkirkby commented on test_alignment.rb
> +  def test_align_it_insert
It looks like the Ruby wrapper for `align_it` sets up the scoring matrix incorrectly. (Matches and mismatches score the same.) Make this test fail, by using the same expectation as the Python code, and then mark it as ignored with a link to the issue. (I'll write up an issue.) We'll have to check whether `align_it` actually gets called by Recall or the upload scripts. (Hopefully not.) Then we can fix it or remove it.

2020-02-25 18:36 UTC, donkirkby commented on test_alignment.rb
> +  #########################################
Do we need the Python flavour from Ruby?

2020-02-25 18:46 UTC, jamesnakagawa commented on test_alignment.rb
> +  def test_align_it_insert
Oh, it definitely definitely does. Upload scripts for sure - maybe Recall, too.

2020-02-25 18:47 UTC, donkirkby commented on test_alignment.rb
> +  def test_align_it_insert
OK, I was wrong. The scores are supposed to both be positive. It's just that the Python scores are higher than the Ruby ones, so you need to scale down your gap penalties. Check what penalties we call with in Recall or the upload scripts, but I would guess 3 and 1 for similar behaviour to the Python wrapper.

2020-02-25 18:48 UTC, jamesnakagawa commented on test_alignment.rb
> +  # end
Ok, I'll delete.

2020-02-25 21:27 UTC, nathanielknight approved these changes

2020-02-26 16:46 UTC, donkirkby approved these changes

2020-02-26 21:01 UTC, merged